<select class="basic-select sm-form-control custom-select countrycode" style="width:100%" name="countrycode" id="inquiry-countrycode">
    <option value="+91" data-flag="in" selected="selected">+91 (IN)</option>
    <option value="+971" data-flag="ae">+971 (AE)</option>
    <option value="+213" data-flag="dz">+213 (DZ)</option>
    <option value="+376" data-flag="ad">+376 (AD)</option>
    <option value="+244" data-flag="ao">+244 (AO)</option>
    <option value="+1264" data-flag="ai">+1264 (AI)</option>
    <option value="+1268" data-flag="ag">+1268 (AG)</option>
    <option value="+54" data-flag="ar">+54 (AR)</option>
    <option value="+374" data-flag="am">+374 (AM)</option>
    <option value="+297" data-flag="aw">+297 (AW)</option>
    <option value="+61" data-flag="au">+61 (AU)</option>
    <option value="+43" data-flag="at">+43 (AT)</option>
    <option value="+994" data-flag="az">+994 (AZ)</option>
    <option value="+1242" data-flag="bs">+1242 (BS)</option>
    <option value="+973" data-flag="bh">+973 (BH)</option>
    <option value="+880" data-flag="bd">+880 (BD)</option>
    <option value="+1246" data-flag="bb">+1246 (BB)</option>
    <option value="+375" data-flag="by">+375 (BY)</option>
    <option value="+32" data-flag="be">+32 (BE)</option>
    <option value="+501" data-flag="bz">+501 (BZ)</option>
    <option value="+229" data-flag="bj">+229 (BJ)</option>
    <option value="+1441" data-flag="bm">+1441 (BM)</option>
    <option value="+975" data-flag="bt">+975 (BT)</option>
    <option value="+591" data-flag="bo">+591 (BO)</option>
    <option value="+387" data-flag="ba">+387 (BA)</option>
    <option value="+267" data-flag="bw">+267 (BW)</option>
    <option value="+55" data-flag="br">+55 (BR)</option>
    <option value="+673" data-flag="bn">+673 (BN)</option>
    <option value="+359" data-flag="bg">+359 (BG)</option>
    <option value="+226" data-flag="bf">+226 (BF)</option>
    <option value="+257" data-flag="bi">+257 (BI)</option>
    <option value="+855" data-flag="kh">+855 (KH)</option>
    <option value="+237" data-flag="cm">+237 (CM)</option>
    <option value="+1" data-flag="ca">+1 (CA)</option>
    <option value="+238" data-flag="cv">+238 (CV)</option>
    <option value="+1345" data-flag="ky">+1345 (KY)</option>
    <option value="+236" data-flag="cf">+236 (CF)</option>
    <option value="+56" data-flag="cl">+56 (CL)</option>
    <option value="+86" data-flag="cn">+86 (CN)</option>
    <option value="+57" data-flag="co">+57 (CO)</option>
    <option value="+269" data-flag="km">+269 (KM)</option>
    <option value="+242" data-flag="cg">+242 (CG)</option>
    <option value="+682" data-flag="ck">+682 (CK)</option>
    <option value="+506" data-flag="cr">+506 (CR)</option>
    <option value="+385" data-flag="hr">+385 (HR)</option>
    <option value="+53" data-flag="cu">+53 (CU)</option>
    <option value="+90392" data-flag="cy">+90392 (CY)</option>
    <option value="+357" data-flag="cy">+357 (CY)</option>
    <option value="+42" data-flag="cz">+42 (CZ)</option>
    <option value="+45" data-flag="dk">+45 (DK)</option>
    <option value="+253" data-flag="dj">+253 (DJ)</option>
    <option value="+1809" data-flag="dm">+1809 (DM)</option>
    <option value="+1809" data-flag="do">+1809 (DO)</option>
    <option value="+593" data-flag="ec">+593 (EC)</option>
    <option value="+20" data-flag="eg">+20 (EG)</option>
    <option value="+503" data-flag="sv">+503 (SV)</option>
    <option value="+240" data-flag="gq">+240 (GQ)</option>
    <option value="+291" data-flag="er">+291 (ER)</option>
    <option value="+372" data-flag="ee">+372 (EE)</option>
    <option value="+251" data-flag="ethiopia">+251 (Ethiopia)</option>
    <option value="+500" data-flag="et">+500 (ET)</option>
    <option value="+298" data-flag="fo">+298 (FO)</option>
    <option value="+679" data-flag="fj">+679 (FJ)</option>
    <option value="+358" data-flag="fi">+358 (FI)</option>
    <option value="+33" data-flag="fr">+33 (FR)</option>
    <option value="+594" data-flag="gf">+594 (GF)</option>
    <option value="+689" data-flag="pf">+689 (PF)</option>
    <option value="+241" data-flag="ga">+241 (GA)</option>
    <option value="+220" data-flag="gm">+220 (GM)</option>
    <option value="+7880" data-flag="ge">+7880 (GE)</option>
    <option value="+49" data-flag="de">+49 (DE)</option>
    <option value="+233" data-flag="gh">+233 (GH)</option>
    <option value="+350" data-flag="gi">+350 (GI)</option>
    <option value="+30" data-flag="gr">+30 (GR)</option>
    <option value="+299" data-flag="gl">+299 (GL)</option>
    <option value="+1473" data-flag="gd">+1473 (GD)</option>
    <option value="+590" data-flag="gp">+590 (GP)</option>
    <option value="+671" data-flag="gu">+671 (GU)</option>
    <option value="+502" data-flag="gt">+502 (GT)</option>
    <option value="+224" data-flag="gn">+224 (GN)</option>
    <option value="+245" data-flag="gw">+245 (GW)</option>
    <option value="+592" data-flag="gy">+592 (GY)</option>
    <option value="+509" data-flag="ht">+509 (HT)</option>
    <option value="+504" data-flag="hn">+504 (HN)</option>
    <option value="+852" data-flag="hk">+852 (HK)</option>
    <option value="+36" data-flag="hu">+36 (HU)</option>
    <option value="+354" data-flag="is">+354 (IS)</option>
    <option value="+62" data-flag="id">+62 (ID)</option>
    <option value="+98" data-flag="ir">+98 (IR)</option>
    <option value="+964" data-flag="iq">+964 (IQ)</option>
    <option value="+353" data-flag="ie">+353 (IE)</option>
    <option value="+972" data-flag="il">+972 (IL)</option>
    <option value="+39" data-flag="it">+39 (IT)</option>
    <option value="+1876" data-flag="jm">+1876 (JM)</option>
    <option value="+81" data-flag="jp">+81 (JP)</option>
    <option value="+962" data-flag="jo">+962 (JO)</option>
    <option value="+7" data-flag="kz">+7 (KZ)</option>
    <option value="+254" data-flag="ke">+254 (KE)</option>
    <option value="+686" data-flag="ki">+686 (KI)</option>
    <option value="+850" data-flag="kp">+850 (KP)</option>
    <option value="+82" data-flag="kr">+82 (KR)</option>
    <option value="+965" data-flag="kw">+965 (KW)</option>
    <option value="+996" data-flag="kg">+996 (KG)</option>
    <option value="+856" data-flag="la">+856 (LA)</option>
    <option value="+371" data-flag="lv">+371 (LV)</option>
    <option value="+961" data-flag="lb">+961 (LB)</option>
    <option value="+266" data-flag="ls">+266 (LS)</option>
    <option value="+231" data-flag="lr">+231 (LR)</option>
    <option value="+218" data-flag="ly">+231 (LY)</option>
    <option value="+417" data-flag="li">+417 (LI)</option>
    <option value="+370" data-flag="lt">+370 (LT)</option>
    <option value="+352" data-flag="lu">+352 (LU)</option>
    <option value="+853" data-flag="mo">+853 (MO)</option>
    <option value="+389" data-flag="mk">+389 (MK)</option>
    <option value="+261" data-flag="mg">+261 (MG)</option>
    <option value="+265" data-flag="mw">+265 (MW)</option>
    <option value="+60" data-flag="my">+60 (MY)</option>
    <option value="+960" data-flag="mv">+960 (MV)</option>
    <option value="+223" data-flag="ml">+223 (ML)</option>
    <option value="+356" data-flag="mt">+356 (MT)</option>
    <option value="+692" data-flag="mh">+692 (MH)</option>
    <option value="+596" data-flag="mq">+596 (MQ)</option>
    <option value="+222" data-flag="mr">+222 (MR)</option>
    <option value="+269" data-flag="yt">+269 (YT)</option>
    <option value="+52" data-flag="mx">+52 (MX)</option>
    <option value="+691" data-flag="fm">+691 (FM)</option>
    <option value="+373" data-flag="md">+373 (MD)</option>
    <option value="+377" data-flag="mc">+377 (MC)</option>
    <option value="+976" data-flag="mn">+976 (MN)</option>
    <option value="+1664" data-flag="ms">+1664 (MS)</option>
    <option value="+212" data-flag="morocco">+212 (Morocco)</option>
    <option value="+258" data-flag="mz">+258 (MZ)</option>
    <option value="+95" data-flag="mn">+95 (MN)</option>
    <option value="+264" data-flag="na">+264 (NA)</option>
    <option value="+674" data-flag="nr">+674 (NR)</option>
    <option value="+977" data-flag="np">+977 (NP)</option>
    <option value="+31" data-flag="nl">+31 (NL)</option>
    <option value="+687" data-flag="nc">+687 (NC)</option>
    <option value="+64" data-flag="nz">+64 (NZ)</option>
    <option value="+505" data-flag="ni">+505 (NI)</option>
    <option value="+227" data-flag="ne">+227 (NE)</option>
    <option value="+234" data-flag="ng">+234 (NG)</option>
    <option value="+683" data-flag="nu">+683 (NU)</option>
    <option value="+672" data-flag="nf">+672 (NF)</option>
    <option value="+670" data-flag="np">+670 (NP)</option>
    <option value="+47" data-flag="no">+47 (NO)</option>
    <option value="+968" data-flag="om">+968 (OM)</option>
    <option value="+680" data-flag="pw">+680 (PW)</option>
    <option value="+507" data-flag="pa">+507 (PA)</option>
    <option value="+675" data-flag="pg">+675 (PG)</option>
    <option value="+595" data-flag="py">+595 (PY)</option>
    <option value="+51" data-flag="pe">+51 (PE)</option>
    <option value="+63" data-flag="ph">+63 (PH)</option>
    <option value="+48" data-flag="pl">+48 (PL)</option>
    <option value="+351" data-flag="pt">+351 (PT)</option>
    <option value="+1787" data-flag="pr">+1787 (PR)</option>
    <option value="+974" data-flag="qa">+974 (QA)</option>
    <option value="+262" data-flag="re">+262 (RE)</option>
    <option value="+40" data-flag="ro">+40 (RO)</option>
    <option value="+7" data-flag="ru">+7 (RU)</option>
    <option value="+250" data-flag="rw">+250 (RW)</option>
    <option value="+378" data-flag="sm">+378 (SM)</option>
    <option value="+239" data-flag="st">+239 (ST)</option>
    <option value="+966" data-flag="sa">+966 (SA)</option>
    <option value="+221" data-flag="sn">+221 (SN)</option>
    <option value="+381" data-flag="cs">+381 (CS)</option>
    <option value="+248" data-flag="sc">+248 (SC)</option>
    <option value="+232" data-flag="sl">+232 (SL)</option>
    <option value="+65" data-flag="sg">+65 (SG)</option>
    <option value="+421" data-flag="sk">+421 (SK)</option>
    <option value="+386" data-flag="si">+386 (SI)</option>
    <option value="+677" data-flag="sb">+677 (SB)</option>
    <option value="+252" data-flag="so">+252 (SO)</option>
    <option value="+27" data-flag="za">+27 (ZA)</option>
    <option value="+34" data-flag="es">+34 (ES)</option>
    <option value="+94" data-flag="lk">+94 (LK)</option>
    <option value="+290" data-flag="sh">+290 (SH)</option>
    <option value="+1869" data-flag="kn">+1869 (KN)</option>
    <option value="+1758" data-flag="sc">+1758 (SC)</option>
    <option value="+249" data-flag="sd">+249 (SD)</option>
    <option value="+597" data-flag="sr">+597 (SR)</option>
    <option value="+268" data-flag="sz">+268 (SZ)</option>
    <option value="+46" data-flag="se">+46 (SE)</option>
    <option value="+41" data-flag="ch">+41 (CH)</option>
    <option value="+963" data-flag="si">+963 (SI)</option>
    <option value="+886" data-flag="tw">+886 (TW)</option>
    <option value="+7" data-flag="tj">+7 (TJ)</option>
    <option value="+66" data-flag="th">+66 (TH)</option>
    <option value="+228" data-flag="tg">+228 (TG)</option>
    <option value="+676" data-flag="to">+676 (TO)</option>
    <option value="+1868" data-flag="tt">+1868 (TT)</option>
    <option value="+216" data-flag="tn">+216 (TN)</option>
    <option value="+90" data-flag="tr">+90 (TR)</option>
    <option value="+7" data-flag="tm">+7 (TM)</option>
    <option value="+993" data-flag="tm">+993 (TM)</option>
    <option value="+1649" data-flag="tc">+1649 (TC)</option>
    <option value="+688" data-flag="tv">+688 (TV)</option>
    <option value="+256" data-flag="ug">+256 (UG)</option>
    <option value="+44" data-flag="gb">+44 (GB)</option>
    <option value="+380" data-flag="ua">+380 (UA)</option>
    <option value="+598" data-flag="uy">+598 (UY)</option>
    <option value="+1" data-flag="us">+1 (US)</option>
    <option value="+7" data-flag="uz">+7 (UZ)</option>
    <option value="+678" data-flag="vu">+678 (VU)</option>
    <option value="+379" data-flag="va">+379 (VA)</option>
    <option value="+58" data-flag="ve">+58 (VE)</option>
    <option value="+84" data-flag="vn">+84 (VN)</option>
    <option value="+84" data-flag="vg">+1284 (VG)</option>
    <option value="+84" data-flag="vi">+1340 (VI)</option>
    <option value="+681" data-flag="wf">+681 (WF)</option>
    <option value="+969" data-flag="ye">+969 (YE)</option>
    <option value="+967" data-flag="ye">+967 (YE)</option>
    <option value="+260" data-flag="zm">+260 (ZM)</option>
    <option value="+263" data-flag="zw">+263 (ZW)</option>
</select>

